# Generated by Django 4.1 on 2022-09-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscriber'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscriber',
            constraint=models.CheckConstraint(check=models.Q(('user', models.F('author')), _negated=True), name='user_is_not_author'),
        ),
    ]
