# Generated by Django 4.1 on 2022-10-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredients', through='core.IngredientAmount', to='core.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
