# Generated by Django 4.1 on 2022-10-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_ingredientamount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='count',
        ),
    ]
