# Generated by Django 4.1 on 2022-10-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscriber_user_is_not_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
